version: '3.8'

services:
  TempVoice-bot:
    build:
      context: .         # Pfad zum Projektverzeichnis
      dockerfile: Dockerfile  # Optional, wenn deine Datei so heißt

    container_name: tempvoice-bot
    restart: unless-stopped

    env_file:
      - .env

    volumes:
      - ./config:/app/config

    working_dir: /app
